backend:
  name: github
  repo: blog.precisionpcs.net
  branch: main
  auth_type: pkce
  client_id: Ov23li9Q9bCDRi4B9VmU
  base_url: https://dev-3hta1oiqk0o014bz.us.auth0.com
  auth_endpoint: /authorize
  token_endpoint: /oauth/token

media_folder: "public/uploads"
public_folder: "/uploads"


collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    publish_mode: editorial_workflow
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "pubDate"
        widget: "datetime"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Author"
        name: "author"
        widget: "string"
        default: "Ethan Phillips"
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
